Feat: UserGo uint64 variables checked, Also methods Find and Update parameters updated in uint64, also updated user displayed modified.
Receipt.go uses contents and amount and client id, initialized variables checked but stills has a problem in the gorm database implementation. Also uint parameters in the uint64 deleteAReceipt method uses uint64
Client.Go uint64 variables updated. Users controller doesn't parses any more for FindUserByID user related to the modification with the types. TokenID Validation also doesn't uses parsing any more.

Error: modification in getClients end point wich didn't called the correct one.
Create receipt doesnt receives a uid any more, due the receipt implementation didn't worked as expected.